version: "3.7"
services:
  app:
    container_name: user-services
    environment:
      - DATABASE_URL=mongodb://mongo:27017/test
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4.0.14
    volumes:
      - ~/data:/data/db
    ports:
      - "27017:27017"